// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Validação das variáveis de ambiente
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missingVars = [];
  if (!SUPABASE_URL) missingVars.push('VITE_SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missingVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  
  const errorMessage = `❌ ERRO: Variáveis de ambiente obrigatórias não configuradas: ${missingVars.join(', ')}\n` +
    `Configure essas variáveis no arquivo .env na raiz do projeto.\n` +
    `Exemplo:\n` +
    `VITE_SUPABASE_URL=https://seu-projeto.supabase.co\n` +
    `VITE_SUPABASE_PUBLISHABLE_KEY=sua-chave-publica`;
  
  // Em build time, lança erro para quebrar o build
  if (import.meta.env.MODE === 'production' || import.meta.env.PROD) {
    throw new Error(errorMessage);
  }
  
  // Em desenvolvimento, apenas avisa mas não quebra
  console.error(errorMessage);
  console.warn('⚠️ O build falhará em produção se essas variáveis não estiverem configuradas.');
}

// Aviso sobre problema de localStorage entre localhost e IP
if (typeof window !== 'undefined') {
  const hostname = window.location.hostname;
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    const hasSession = localStorage.getItem('apex-glass-auth') || 
                       Object.keys(localStorage).some(key => key.includes('supabase') && key.includes('auth'));
    
    if (!hasSession) {
      console.warn('💡 DICA: Se você fez login usando o IP (ex: 192.168.x.x:8081), precisa usar a mesma URL para manter a sessão.');
      console.warn('   O localStorage é separado por origem (localhost ≠ IP). Sempre use a mesma URL para acessar o sistema.');
    }
  }
}

// Garantir que as variáveis existem e não são placeholders
const isPlaceholder = (value: string | undefined) => {
  return !value || 
         value === 'placeholder-key' || 
         value === 'https://placeholder.supabase.co' ||
         value.startsWith('sua-') ||
         value.startsWith('seu-');
};

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || 
    isPlaceholder(SUPABASE_URL) || isPlaceholder(SUPABASE_PUBLISHABLE_KEY)) {
  // Se chegou aqui em produção, já lançou erro acima
  // Em desenvolvimento, ainda permite continuar com placeholders para não quebrar o dev server
  if (import.meta.env.MODE === 'production' || import.meta.env.PROD) {
    throw new Error('Variáveis de ambiente do Supabase são obrigatórias e não podem ser placeholders');
  }
}

// Log de diagnóstico (apenas em desenvolvimento)
if (import.meta.env.DEV) {
  console.log('🔍 Diagnóstico Supabase:', {
    url: SUPABASE_URL ? `${SUPABASE_URL.substring(0, 30)}...` : '❌ Não configurado',
    key: SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}...` : '❌ Não configurado',
    keyLength: SUPABASE_PUBLISHABLE_KEY?.length || 0,
  });
}

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: 'apex-glass-auth', // Chave fixa para evitar problemas entre origens
      flowType: 'pkce', // Usar PKCE para melhor segurança e estabilidade
    },
    global: {
      headers: {
        'x-client-info': 'apex-glass-erp@1.0.0',
      },
    },
  }
);