// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Validação das variáveis de ambiente
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('⚠️ Variáveis do Supabase não configuradas. Configure o arquivo .env');
  console.warn('VITE_SUPABASE_URL:', SUPABASE_URL ? '✅' : '❌');
  console.warn('VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✅' : '❌');
}

// Aviso sobre problema de localStorage entre localhost e IP
if (typeof window !== 'undefined') {
  const hostname = window.location.hostname;
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    const hasSession = localStorage.getItem('apex-glass-auth') || 
                       Object.keys(localStorage).some(key => key.includes('supabase') && key.includes('auth'));
    
    if (!hasSession) {
      console.warn('💡 DICA: Se você fez login usando o IP (ex: 192.168.x.x:8081), precisa usar a mesma URL para manter a sessão.');
      console.warn('   O localStorage é separado por origem (localhost ≠ IP). Sempre use a mesma URL para acessar o sistema.');
    }
  }
}

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: 'apex-glass-auth', // Chave fixa para evitar problemas entre origens
    }
  }
);